# Generated by Django 5.2.4 on 2025-11-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0002_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
